---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Configurar host do lab ansible
      lineinfile: line "{{item}}" path=/etc/hosts
      with_items:
        - 192.168.33.10 control-node
        - 192.168.33.11 app01
        - 192.168.33.12 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql