# -*- mode: ruby -*-
Vagrant.configure("2") do |config|

  config.vm.box = "Centos/7"
  config.vm.hostname = "docker"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.network "private_network", ip: "192.168.34.12"
  config.vm.network "forwarded_port", guest: 22, host: 2230, host_ip: "127.0.0.1"
  
end
